name: text_speak

description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5

  cupertino_icons: ^1.0.2
  avatar_glow: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_tts: ^4.0.2

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  
